FaceAttend/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import login_success
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attendance.urls', namespace='attendance')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login_success/', login_success, name='login_success')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('courses/', views.CoursesList.as_view(), name='courses'),
    path('courses/add/', views.CourseCreate.as_view(), name='course_create'),
    path('my_courses/', views.EnrolmentList.as_view(), name='my_courses'),
    path('course/<int:pk>/drop/', views.EnrolmentDelete.as_view(), name='course_drop'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course_delete'),
    path('register_course/', views.EnrolmentCreate.as_view(), name='register_course'),
    path('attendance/<int:pk>/', views.AttendanceList.as_view(), name='attendance'),
    path('live_attendance/<int:pk>/', views.AttendanceLive.as_view(), name='live_attendance'),
    path('manual_attendance/', views.AttendanceCreate.as_view(), name='manual_attendance'),

    # Ajax
    path('view_attendance/<int:pk>/', views.view_attendance, name='view_attendance'),
    path('update_attendance/', views.update_attendance, name='update_attendance'),
    path('view_proof/<int:pks>/<int:pka>/', views.view_proof, name='view_proof'),

    # Streaming
    path('video_feed/', views.video_feed, name='video_feed'),
]

accounts/models.py
import os
import secrets

from PIL import Image
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    name = models.CharField(_('Full Name'), max_length=255)
    email = models.EmailField(_('Email Address'), unique=True)
    face_pic = models.ImageField(
        _('Choose Profile Picture'), null=True, blank=True,
        help_text='''For students, please upload a photo showing your face.
        This will be used to record your attendance through facial recognition.'''
    )
    is_instructor = models.BooleanField(
        _('I am a Course Instructor'), default=False,
        help_text='''Please check this field only if you are a course instructor.
        For students, please leave this unchecked.'''
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', ]

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.face_pic:
            img = Image.open(self.face_pic.path)
            random_hex = secrets.token_hex(8)
            _, f_ext = os.path.splitext(self.face_pic.path)
            picture_fn = random_hex + f_ext
            picture_path = os.path.join(settings.BASE_DIR, 'media', picture_fn)

            if img.height > 400 or img.width > 400:
                output_size = (400, 400)
                img.thumbnail(output_size)
                os.remove(self.face_pic.path)
                self.face_pic = picture_fn
                img.save(picture_path)
                self.save()

    class Meta:
        db_table = "users"
        verbose_name = _("User")
        verbose_name_plural = _("Users")

    def __str__(self):
        return self.name

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'name', 'is_instructor', 'face_pic')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'name', 'is_instructor', 'face_pic')

accounts/views.py
# from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect

from .forms import CustomUserCreationForm


def login_success(request):
    """
    Redirects users based on whether they are in the admins group
    """
    if request.user.is_instructor:
        # user is an admin
        return redirect('attendance:courses')
    else:
        return redirect('attendance:my_courses')


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

accounts/templates/accounts/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light py-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <a class="navbar-brand" href="{% url 'attendance:home' %}">FaceAttend</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% if user.is_authenticated %}
                {% if user.is_instructor %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'attendance:courses' %}">Courses</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                     <a class="nav-link" href="{% url 'attendance:my_courses' %}">Courses</a>
                    </li>
                {% endif %}

            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            {% if user.is_authenticated %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.name }}
                </a>
                <div class="dropdown-menu" aria-labelledby="accountDropdown">
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>