FaceAttend/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import login_success
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attendance.urls', namespace='attendance')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login_success/', login_success, name='login_success')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('courses/', views.CoursesList.as_view(), name='courses'),
    path('courses/add/', views.CourseCreate.as_view(), name='course_create'),
    path('my_courses/', views.EnrolmentList.as_view(), name='my_courses'),
    path('course/<int:pk>/drop/', views.EnrolmentDelete.as_view(), name='course_drop'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course_delete'),
    path('register_course/', views.EnrolmentCreate.as_view(), name='register_course'),
    path('attendance/<int:pk>/', views.AttendanceList.as_view(), name='attendance'),
    path('live_attendance/<int:pk>/', views.AttendanceLive.as_view(), name='live_attendance'),
    path('manual_attendance/', views.AttendanceCreate.as_view(), name='manual_attendance'),

    # Ajax
    path('view_attendance/<int:pk>/', views.view_attendance, name='view_attendance'),
    path('update_attendance/', views.update_attendance, name='update_attendance'),
    path('view_proof/<int:pks>/<int:pka>/', views.view_proof, name='view_proof'),

    # Streaming
    path('video_feed/', views.video_feed, name='video_feed'),
]

attendance/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.utils.text import slugify


class Course(models.Model):
    name = models.CharField(_('Course Name'), max_length=100, unique=True)
    slug = models.SlugField(_('Course Slug'), max_length=255, unique=True, default='', editable=False)
    students = models.ManyToManyField(get_user_model(), related_name='courses_taken', through='Enrolment')
    instructor = models.ForeignKey(get_user_model(), related_name='courses_instructed', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    class Meta:
        db_table = "course"
        verbose_name = _("Course")
        verbose_name_plural = _("Courses") # Translate to multiple languages if necessary

    def __str__(self):
        return self.name


class Enrolment(models.Model):
    # Pivot table: links courses and students through m:n relationship
    student = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    course = models.ForeignKey('attendance.Course', related_name='enrolments', on_delete=models.CASCADE)
    date_enrolled = models.DateTimeField(_('Date Enrolled'), auto_now_add=True)

    class Meta:
        db_table = "enrolment"
        verbose_name = _("Enrolment")
        verbose_name_plural = _("Enrolment")
        unique_together = ('student', 'course',)

    def __str__(self):
        return f'{self.course} Enrolment'


class Attendance(models.Model):
    course = models.ForeignKey('attendance.Course', on_delete=models.CASCADE, related_name='attendance')
    students = models.ManyToManyField(get_user_model(), through='Proof')
    total_enrolment =  models.IntegerField()
    timestamp = models.DateTimeField(_('Lesson Time'), auto_now_add=True)

    class Meta:
        db_table = "attendance"
        verbose_name = _("Attendance")
        verbose_name_plural = _("Attendance")

    def __str__(self):
        return self.timestamp


class Proof(models.Model):
    # Pivot table: links attendnce and students through m:n relationship
    student = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    attendance = models.ForeignKey('attendance.Attendance', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(_('Date Clocked'), auto_now_add=True)
    proof_pic = models.ImageField(null=True, blank=True)

    class Meta:
        db_table = "attendance_proof"
        verbose_name = _("Attendance Proof")
        verbose_name_plural = _("Attendance Proof")
        unique_together = ('student', 'attendance',)

    def __str__(self):
        return f'{self.attendance} Proof'

attendance/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http.response import StreamingHttpResponse
from .camera import VideoCamera
from .models import Course, Enrolment, Attendance, Proof


class HomePage(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['classes'] = Post.objects.all()
        return context

    template_name = 'attendance/home.html'


# Courses
class CoursesList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self):
        return self.request.user.is_instructor

    model = Course
    context_object_name = 'courses'
    template_name = 'attendance/courses_list.html'

    def get_queryset(self):
        return self.request.user.courses_instructed.all()


class CourseCreate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, CreateView):
    def test_func(self):
        return self.request.user.is_instructor

    success_message = 'Course successfully added'
    template_name = 'attendance/course_create.html'

    model = Course
    fields = ('name',)
    success_url = reverse_lazy('attendance:courses')
    login_url = 'login'

    def form_valid(self, form):
        form.instance.instructor = self.request.user
        return super().form_valid(form)


class CourseDelete(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    def test_func(self):
        return self.request.user.is_instructor

    model = Course
    success_message = 'Course successfully deleted'
    template_name = 'attendance/course_delete.html'
    success_url = reverse_lazy('attendance:courses')


# Enrolment
class EnrolmentList(LoginRequiredMixin, ListView):
    model = Enrolment
    context_object_name = 'enrolments'
    template_name = 'attendance/enrolments_list.html'

    def get_queryset(self):
        return Enrolment.objects.filter(student=self.request.user)


class EnrolmentCreate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, CreateView):
    def test_func(self):
        return not self.request.user.is_instructor

    success_message = 'Course enrolment successful'
    template_name = 'attendance/enrolment_create.html'

    model = Enrolment
    fields = ('course',)
    success_url = reverse_lazy('attendance:my_courses')
    login_url = 'login'

    def form_valid(self, form):
        form.instance.student = self.request.user
        return super().form_valid(form)


class EnrolmentDelete(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    def test_func(self):
        return not self.request.user.is_instructor

    model = Enrolment
    success_message = 'Course successfully dropped'
    template_name = 'attendance/course_drop.html'
    success_url = reverse_lazy('attendance:my_courses')


# Attendance
class AttendanceList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self):
        return self.request.user.is_instructor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = Course.objects.get(pk=self.kwargs['pk'])
        attendance = course.attendance.first()
        context['course'] = course
        context['attendance'] = attendance
        return context

    model = Attendance
    context_object_name = 'attendance_list'
    template_name = 'attendance/attendance_list.html'


class AttendanceLive(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    def test_func(self):
        return self.request.user.is_instructor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = Course.objects.get(pk=self.kwargs['pk'])
        attendance = Attendance.objects.create(course=course, total_enrolment=course.students.count())
        self.request.session['attendance_id'] = attendance.pk
        self.request.session['course_id'] = course.pk
        context['attendance'] = attendance
        return context

    context_object_name = 'course'
    template_name = 'attendance/live_attendance.html'

    model = Course
    login_url = 'login'


class AttendanceCreate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, CreateView):
    def test_func(self):
        return self.request.user.is_instructor

    template_name = 'attendance/manual_attendance.html'
    success_message = 'Course enrolment successful'
    fields = ('student',)

    model = Proof
    login_url = 'login'
    success_url = reverse_lazy('attendance:courses')

    def form_valid(self, form):
        form.instance.attendance_id = self.request.session['attendance_id']
        return super().form_valid(form)


def gen(camera, attendance_id, course_id):
    while True:
        frame = camera.get_frame(attendance_id, course_id)
        yield (b'...frame\r\n'
               b'Content-Type: image/jpg\r\n\r\n' + frame + b'\r\n\r\n')


def video_feed(request):
    attendance_id = request.session['attendance_id']
    course_id = request.session['course_id']
    return StreamingHttpResponse(gen(VideoCamera(), attendance_id, course_id),
                                 content_type='multipart/x-mixed-replace; boundary=frame')


# Ajax routes
def update_attendance(request):
    attendance = Attendance.objects.get(pk=request.session['attendance_id'])
    return render(request, 'attendance/ajax/update_attendance.html', {
        'attendance': attendance
    })


def view_attendance(request, pk=None):
    attendance = Attendance.objects.get(pk=pk)
    return render(request, 'attendance/ajax/attendance.html', {
        'attendance': attendance
    })


def view_proof(request, pks=None, pka=None):
    proof = Proof.objects.get(student_id=pks, attendance_id=pka)
    return render(request, 'attendance/ajax/proof.html', {
        'proof': proof
    })

attendance/templates/attendance/attendance_capture.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block title %}Record Attendance{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- Record Attendance -->
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <p class="h3 card-header text-center">Record Attendance</p>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-block btn-lg">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
</div>
{% endblock content %}

attendance/templates/attendance/attendance_list.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block title %}Attendance Record{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- NEW LESSON -->
    <div class="row">
        <div class="col-md-4">
            <div class="border p-4">
                {% for attendance in course.attendance.all %}
                    <p class="h5 my-3">
                        <a class="attendance_view" href="{% url 'attendance:view_attendance' pk=attendance.pk %}">{{ attendance.timestamp }}</a>
                    </p>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-8">
            <div class="border p-4">
                <span id="render"></span>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
$(document).ready(function () {
    $('#render').html(`<p class="h4 text-success text-center">Click an entry on left to load data</p>`)
    $(document).on('click', '.attendance_view', function (e) {
        e.preventDefault()
        $("a.attendance_view").removeClass("active");
        $(this).addClass('active')
        var link =  $(this).attr('href')
        $.ajax({
            type: 'GET',
            url: link,
            success: function (res) {
                $('#render').html(res)
                console.log(res)
            }
        })
    })

    $(document).on('click', '.proof', function (e) {
        e.preventDefault()
        $("a.proof").removeClass("active");
        $(this).addClass('active')
        var url =  $(this).attr('href')
        $.ajax({
            type: 'GET',
            url: url,
            success: function (res) {
                $('#render_proof').html(res)
                console.log(res)
            }
        })
    })
})
</script>
{% endblock javascript %}

attendance/templates/attendance/course_create.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Add Course{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- ADD COURSE -->
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <p class="h3 card-header text-center">Add Course</p>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-block btn-lg">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
</div>
{% endblock content %}

attendance/templates/attendance/course_delete.html
{% extends 'accounts/base.html' %}

{% block title %}Delete Course Confirmation{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- ADD COURSE -->
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <p class="h3 card-header text-center">Delete Course Confirmation</p>
                <div class="card-body">
                    <p>Hi {{ user.name }}, we thought it fair to let you confirm that you intend to delete this course. Please note that deleting this course will permanently delete all records associated with it, including students enrolments and attendance records.</p>
                    <form method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-block btn-lg">Confirm Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
</div>
{% endblock content %}

attendance/templates/attendance/course_drop.html
{% extends 'accounts/base.html' %}

{% block title %}Drop Course Confirmation{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- ADD COURSE -->
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <p class="h3 card-header text-center">Drop Course Confirmation</p>
                <div class="card-body">
                    <p>Hi {{ user.name }}, we thought it fair to let you confirm that you intend to drop this course. Please note that this action is irreversible.</p>
                    <form method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-block btn-lg">Confirm Drop</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
</div>
{% endblock content %}

attendance/templates/attendance/courses_list.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Courses{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- COURSES -->
    <p class="h3 text-center">Courses under Me</p>
    {% if user.is_instructor %}
    <div class="my-2 text-right">
        <a href="{% url 'attendance:course_create' %}" class="btn btn-primary">Add Course</a>
    </div>
    {% endif %}
    <table class="table table-bordered">
        {% include 'attendance/partials/_messages.html' %}
        <thead>
            <tr>
                <th>Course Name</th>
                <th>Students Enrolled</th>
                <th>Start Lesson</th>
                <th>Attendance</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% if courses %}
            {% for course in courses %}
            <tr>
                <td>{{ course.name }}</td>
                <td>{{ course.students.count }}</td>
                <td>
                    <a href="{% url 'attendance:live_attendance' pk=course.pk %}" class="btn btn-primary btn-block {% if course.enrolments.count < 1 %}disabled{% endif %}">Start</a>
                </td>
                <td>
                    <a href="{% url 'attendance:attendance' pk=course.pk %}" class="btn btn-success btn-block">Attendance</a>
                </td>
                <td>
                    <a href="{% url 'attendance:course_delete' pk=course.pk %}" class="btn btn-danger btn-block">Delete</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="5" class="text-center text-danger">There are no courses under you yet...</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock content %}

attendance/templates/attendance/enrolment_create.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block title %}Course Registration{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- CAURSE REGISTRATION -->
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <p class="h3 card-header text-center">Course Registration</p>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-block btn-lg">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
</div>
{% endblock content %}

attendance/templates/attendance/enrolments_list.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% block title %}My Current Units{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- ENROLMENT -->
    <p class="h3 text-center">My Current Units</p>
    <div class="my-2 text-right">
        <a href="{% url 'attendance:register_course' %}" class="btn btn-primary">Register New Course</a>
    </div>
    <table class="table table-bordered">
    {% include 'attendance/partials/_messages.html' %}
        <thead>
            <tr>
                <th>Course</th>
                <th>Date Enrolled</th>
                <th>Drop Course</th>
            </tr>
        </thead>
        <tbody>

            {% if enrolments %}
            {% for enrolment in enrolments %}
            <tr>
                <td>{{ enrolment }}</td>
                <td>{{ enrolment.date_enrolled }}</td>
                <td>
                    <a href="{% url 'attendance:course_drop' pk=enrolment.pk %}" class="btn btn-danger btn-block">Drop</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3" class="text-center text-danger">You have not enrolled for any course yet...</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock content %}

attendance/templates/attendance/home.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- HOME -->
    <div class="jumbotron text-center">
        <h1 class="display-4">Welcome to FAceAttend</h1>
        <p class="lead">FaceAttend is an automated class attendance register...</p>
        <hr class="my-4">
        {% if not user.is_authenticated %}
            <a class="btn btn-primary btn-lg" href="{% url 'signup' %}" role="button">Sign Up</a>
            <a class="btn btn-success btn-lg" href="{% url 'login' %}" role="button">Login</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
console.log('We are here today...')
</script>
{% endblock javascript %}

attendance/templates/attendance/lesson_create.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block title %}New Lesson{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- NEW LESSON -->
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <p class="h3 card-header text-center">New Lesson</p>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-block btn-lg">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock content %}

attendance/templates/attendance/lessons_list.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Lessons{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- LESSONS -->
    <p class="h3 text-center">Scheduled Lessons</p>
    {% if user.is_instructor %}
    <div class="my-2 text-right">
        <a href="{% url 'attendance:lesson_create' %}" class="btn btn-primary">Add Lesson</a>
    </div>
    {% endif %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Lesson</th>
                <th>Start</th>
                <th>Attendance</th>
            </tr>
        </thead>
        <tbody>

            {% if lessons %}
            {% for lesson in lessons %}
            <tr>
                <td>{{ lesson }}</td>
                <td>
                    <a href="{% url 'attendance:live_attendance' lesson_id=lesson.pk %}" class="btn btn-primary btn-block">Start</a>
                </td>
                <td></td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3" class="text-center text-danger">No lessons yet...</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock content %}

attendance/templates/attendance/live_attendance.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block title %}Live Attendance{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- Live Attendance -->
    <div class="row">
        <div class="col-md-8">
            <img src="{% url 'attendance:video_feed' %}" alt="" width="100%">
            <div class="my-4 mx-auto d-flex justify-content-between">
                <div>
                    <a href="{% url 'attendance:manual_attendance' %}" class="btn btn-primary px-4">Manual Checkin</a>
                </div>
                <div>
                    <a href="{% url 'attendance:attendance' pk=course.pk %}" class="btn btn-danger px-4">End Session</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <span id="render"></span>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
$(document).ready(function () {
    function update_attendance() {
        $.ajax({
            type: 'GET',
            url: {% url 'attendance:update_attendance' %},
            success: function (res) {
                $('#render').html(res)
                console.log(res)
            }
        })
    }

    setInterval(function () {
        update_attendance();
    }, 2000);
})
</script>
{% endblock javascript %}

attendance/templates/attendance/manual_attendance.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Manual Attendance{% endblock %}

{% block content %}
<div class="container my-5">
    <!-- Manual Attendance -->
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                {% include 'attendance/partials/_messages.html' %}
                <p class="h3 card-header text-center">Manual Attendance</p>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-block btn-lg">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
</div>
{% endblock content %}